### ISSUE TITLE
Nonce not present on JTW if user has Microsoft Authenticator app installed

### ISSUE THREAD

**Issue by gmarques33** [AzureAD/microsoft-authentication-library-for-android#1951]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android Version: Android 14
 - MSAL Version: 4.9.0
 
**To Reproduce**
We're using the following call to authenticate:
 
```kotlin
PublicClientApplication.createSingleAccountPublicClientApplication(this, R.raw.auth_config_single_account).acquireToken(
  AcquireTokenParameters
    .Builder()
    .withPrompt(SELECT_ACCOUNT)
    .withAuthorizationQueryStringParameters(listOf(SimpleEntry("nonce", nonce)))
    .withScopes(listOf(EMAIL_SCOPE))
    .startAuthorizationFromActivity(activity)
    .withCallback(object : AuthenticationCallback {
      override fun onSuccess(authenticationResult: IAuthenticationResult) {
        continuation.resume(authenticationResult.account.idToken!!)
      }

      override fun onError(exception: MsalException) {
        continuation.resumeWithException(exception)
      }

      override fun onCancel() {
        continuation.cancel()
      }
    })
    .build()
)
```
if the user has the Microsoft Authenticator app installed the token doesn't contain the `nonce` that we pass on ` .withAuthorizationQueryStringParameters(listOf(SimpleEntry("nonce", nonce)))`. If the user doesn't have the Microsoft Authenticator the login is done in an Chrome Custom Tab and the token will have the nonce as expected.

**Comment by melissaahn** [comment]
Hi, this issue should be resolved with the next release of Authenticator (should be version 6.2502.+).

**Comment by gmarques33** [comment]
Hi, I updated to the latest version of the app (6.2504.2510) and I'm still not getting the nonce.
