### ISSUE TITLE
BrowserAuthorizationFragment.createCustomTabResponseIntent crash NullPointerException

### ISSUE THREAD

**Issue by andj207** [AzureAD/microsoft-authentication-library-for-android#975]
**Describe the bug**
My app is live and got this bug when use start sign in, the bug was reported in Firebase Crashlystic

**Smartphone (please complete the following information):**
 - Device: Xperia X
 - Android Version: 8.0.0
 - Browser: don't know
 - MSAL Version: 1.4.0

**Stacktrace**
    
    Caused by java.lang.NullPointerException
    Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
    android.content.ComponentName.<init> (ComponentName.java:131)
    android.content.Intent.<init> (Intent.java:5698)
    com.microsoft.identity.common.internal.providers.oauth2.BrowserAuthorizationFragment.createCustomTabResponseIntent (BrowserAuthorizationFragment.java:77)
    com.microsoft.identity.client.BrowserTabActivity.onCreate (BrowserTabActivity.java:64)
    android.app.Activity.performCreate (Activity.java:6975)
    android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
    android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2778)
    android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2900)
    android.app.ActivityThread.-wrap11 (ActivityThread.java)
    android.app.ActivityThread$H.handleMessage (ActivityThread.java:1601)
    android.os.Handler.dispatchMessage (Handler.java:105)
    android.os.Looper.loop (Looper.java:251)
    android.app.ActivityThread.main (ActivityThread.java:6589)
    java.lang.reflect.Method.invoke (Method.java)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
    com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

**To Reproduce**
- Start user authentication screen

**Expected behavior**
User can signed in

**Actual Behavior**
Crash because of this error

**Additional context**
This bug is a random crash. Not all users have it. I checked the code where it crashes, the `sCallingActivityClass` static field was `null` that was used before it is set by `BrowserAuthorizationFragment.createCustomTabResponseIntent(..)`

**Comment by shahzaibj** [comment]
@andj207 Thanks for reporting. We are aware of this issue and we've fixed it here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/970/files

The fix will be going out in the next release of MSAL that is currently scheduled for the end of this month.

**Comment by shahzaibj** [comment]
@andj207 We've fixed this in MSAL v1.5.0 
https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.5.0

**Comment by fatihsokmen** [comment]
You didn't solve the issue. You show a toast only if it is null.

**Comment by shahzaibj** [comment]
@fatihsokmen That is not possible because the app that started the request has died i.e. the app containing MSAL has died and cannot finish the request. The server has already sent the auth code but the app wasn't available to accept it and thus the request cannot be completed. Even if there was a way to somehow complete the authorization and get the auth code, then who would get that auth code and exchange for a token? The app is just not there to accept the result anyway. 

We did solve the issue of the crash and you should no longer see a Null Pointer Exception.

This is the original PR to fix the issue: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/966

**Comment by fatihsokmen** [comment]
@shahzaibj Can't you check ChromeTab intent in first place whether it is null or not, and then you can choose one of the options - ChromeTab or WebView. This is very common for many sdks - especially payment sdks issuing 3D secure (Web). They check if chrome tab is doable otherwise go with WebView.

**Comment by shahzaibj** [comment]
@fatihsokmen We do check it prior to starting an authorization request and decide whether to go with browser/custom tabs or webview. This particular scenario is when the calling app has died in the middle of the request after that decision has already been made and the authorization request was already in progress. We can't change the authorization agent in the middle of the request.

**Comment by fatihsokmen** [comment]
It is not scenario for us, our app is not dying. It's worked all the time until today.

**Comment by pomian17** [comment]
@shahzaibj, we are also facing this bug. There are some devices (e.g. Xiaomi Mi A2 lite, Huawei P10 lite, LG K4, Polaroid Snap S60, LG X power) that this happens on (no specific Android version, seems to happen on all of them)
Scenario is as follows:
1. Open Login/forgot/password/register page (in BrowserAuthorizationFragment)
2. Activity gets killed by system, only browser window remains.
3. Fill in the forms. Click e.g. login to return to app.
4. Activity is recreated, but it has no preserved state, so before app crashed due to  NullPointerException, now it shows toast, but it does not change the fact, that user is not able to be authorized.

It does not happens always, but usually there has to be about 3-4 bug occurences until user is able to proceed.
Maybe there is a way to make this activity able to survive process death?

Also, changing _authorization_user_agent_ setting to WEBVIEW helps, as mentioned in [https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/923](url), but we still have problem in register form, where after clicking privacy policy link, and coming back, activity is restarted. User cannot also change app to other during this process. For example to get code that was sent to email and has to be provided in app. After coming back, registration process is restarted.

**Comment by azakharenka1** [comment]
Any progress with the last issue?

**Comment by shahzaibj** [comment]
@pomian17 / @azakharenka1 When the activity is killed, there is no way to obtain the token anymore as the process in which MSAL was running is dead. There is no longer any ongoing token request in memory. 

This issue only happens on browsers without custom tabs when either the user or the OS kills the app when the authorization request is happening in the browser.

You can workaround this by using a browser that support custom tabs, or as you guys called out, using `WEBVIEW` auhorization agent is also a solution for this. https://docs.microsoft.com/en-us/azure/active-directory/develop/authorization-agents

**Comment by ashokreddynarra** [comment]
Any progress with this issue?


This is still happening on few devices like   HUAWEI Mate SE(OS:8.0),  Galaxy A10e(OS:9), Galaxy S8(OS:9), Galaxy A50( OS :10), Stylo 6(OS:10) and many


Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.conduent.wellcheck/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
       
       **I am using in "react-native-msal": "^2.0.3"**
